name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19

    - name: Build with Gradle
      run: ./gradlew build
